/*
  Francois Goasoue, Univ Rennes, ENSSAT-IRISA
*/

// DO NOT EDIT THIS FILE

/*
  Enumeration for the different actions that the player may choose
 */
enum action_list {NONE, UP, DOWN, LEFT, RIGHT, BOMB_LEFT, BOMB_RIGHT};
typedef enum action_list action;

/*
  Struct-based type for the current level information:
  - map is a two-dimensions array of char representing the EMPTY map
  - map has xsize columns and ysize rows
  - map exit is at column xsize and row ysize
*/
typedef struct
{
  char **map;
  int xsize;
  int ysize;
  int xexit;
  int yexit;
} levelinfo;

/*
    Struct-based type for a character (runner or enemies):
    - item is the ascii char that designates the character
    - x and y provides the character position in the map
    - d is the last action performed by the character (-1 in the beginning)
*/
typedef struct
{
  char item;
  int x;
  int y;
  action d;
} character;

/*
  Linked list for characters
*/
struct character_link
{
  character c;
  struct character_link *next;
};
typedef struct character_link *character_list;

/*
    Struct-based type for a bonuses:
    - x and y provides the bonus position in the map
*/
typedef struct
{
  int x;
  int y;
} bonus;

/*
  Linked list for bonuses
*/
struct bonus_link
{
  bonus b;
  struct bonus_link *next;
};
typedef struct bonus_link *bonus_list;


/*
    Linked list for the bombs
    - x and y provides the bomb position in the map
    - delay is the number of game rounds it remains before the bomb effect ends
*/
struct bomb_link
{
  int x;
  int y;
  int delay;
  struct bomb_link *next;
};
typedef struct bomb_link *bomb_list;

/*
  Function to code (see player.c)
*/
action lode_runner(levelinfo, character_list, bonus_list, bomb_list);

